### ISSUE TITLE
does this tool support ordinary deeplearnning model?

### ISSUE THREAD

**Issue by skyleft** [Mindgard/cli#40]
all the example I can see are target  for llm, I wonder if I can use this tool to test ordinary deeplearning model , such like resnet, yolo?

**Comment by benjiman** [comment]
Hello,

Non-llm models can be tested via our web interface, you can try some at https://sandbox.mindgard.ai . 

CLI support for these models will be coming soon. What model(s) were you hoping to use it to test?

**Comment by skyleft** [comment]
I worked as a cybersecurity engineer for a  leading  new energy vehicle
company in China， and want to see if we can buy your company's tool
to test some AI modles in Intelligent connected vehicles, such as object
detection, segmentation, tracking and so on.

Benji Weber ***@***.***> 于2024年6月13日周四 13:44写道：

**Comment by benjiman** [comment]
We can likely help with this, if you drop me an email at benji at mindgard dot ai we can explore in more detail.

**Comment by skyleft** [comment]
ok, I'll do it

Benji Weber ***@***.***> 于2024年6月13日周四 15:46写道：
