### ISSUE TITLE
Chat bot support

### ISSUE THREAD

**Issue by priamai** [Mindgard/cli#54]
Hi there,
I am the author of the ChatScanner tool for pentesting live chat bots which does not interact with the backend API such as OpenAI but instead via a web application.
I would like to know how can I integrate your tool to directly perform the attacks on a more generic IO loop where I basically send the text prompt and receive the text response.
Thanks!

**Comment by benjiman** [comment]
Hello. We have another tool that can be used together with the Mindgard CLI to test web Chatbots. It's not currently open sourced. If you have a use case for this that you'd like to discuss feel free to contact us via https://mindgard.ai/contact-us or our discord https://discord.gg/qtG9TTs6f7
